services:
  transaction_service:
    build: .
    ports:
      - "${HTTP_HOST_PORT}:5012"
      - "${HTTPS_HOST_PORT}:5002"
    environment:
      - ASPNETCORE_HTTP_PORTS=5012
      - ASPNETCORE_HTTPS_PORTS=5002
      - ConnectionStrings:financedb=${FINANCEDB}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERTIFICATE_PASSWORD}
    volumes:
      - ${APPDATA}/ASP.NET/Https/:/root/.aspnet/https/